import React, { Component } from "react";

export default class Effects extends Component {
  render() {
    return (
      <form>
        <label>
          Delay
          <input
            id={this.props.id}
            name="delay"
            type="text"
            value={this.props.delayTime}
            onChange={this.props.handleEffectChange}
          />
        </label>
        <label>
          Position
          <input
            id={this.props.id}
            name="position"
            value={this.props.position}
            onChange={this.props.handleEffectChange}
          />
        </label>
        <label>
          Panning
          <input
            id={this.props.id}
            name="panning"
            type="text"
            value={this.props.panning}
            onChange={this.props.handleEffectChange}
          />
        </label>
        <ol>
          Reverb
          <li>
            <label>
              Room Size
              <input
                id={this.props.id}
                name="reverb.roomSize"
                type="text"
                value={this.props.reverb.roomSize}
                onChange={this.props.handleEffectChange}
              />
            </label>
          </li>
          <li>
            <label>
              Dampening
              <input
                id={this.props.id}
                name="reverb.dampening"
                type="text"
                value={this.props.reverb.dampening}
                onChange={this.props.handleEffectChange}
              />
            </label>
          </li>
          <li>
            <label>
              Wet
              <input
                id={this.props.id}
                name="reverb.wet"
                type="text"
                value={this.props.reverb.wet}
                onChange={this.props.handleEffectChange}
              />
            </label>
          </li>
          <li>
            <label>
              Dry
              <input
                id={this.props.id}
                name="reverb.dry"
                type="text"
                value={this.props.reverb.dry}
                onChange={this.props.handleEffectChange}
              />
            </label>
          </li>
        </ol>
      </form>
    );
  }
}
